Downgrade once_cell from v1.15.0 to v1.14.0 to try to overcome the msrv failure.
Workflow log:

Downloaded once_cell v1.15.0
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.15.0/Cargo.toml`
Error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.15.0/Cargo.toml`
Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101